name: unit-tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      php_version: "7.3"
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v3
        